name: Lints and Tests

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  # ---
  # --- Run tests and lints
  # ---
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        crate: [".", "opening-hours-syntax"]

    defaults:
      run:
        working-directory: ${{ matrix.crate }}

    steps:
      - uses: actions/checkout@v2

      - name: Display rust version
        run: |
          rustc --version
          cargo clippy -- --version
          cargo fmt -- --version

      - name: Lint
        run: cargo clippy --all-targets -- -D warnings

      - name: Format
        run: cargo fmt -- --check

      - name: Tests
        run: cargo test

  # ---
  # --- Compute coverage and upload to codecov.io
  # ---
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: 0.16.0
          args: '--ignore-panics --ignore-tests'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
